# This workflow will scrap GitHub trending projects daily.
name: single-task-cfcdn-host

on:
  push:
    branches:
#      - master
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]
  schedule:
#     run on every hour
#     - cron: "0 * * * *"
#     run on every 3 hour
#     - cron: "0 */3 * * *"
#     run on every 15 min
#     - cron: "*/45 * * * *"
#     run on 0 and 12 clock
    - cron: "0 4 * * 1"
env:
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  REDIS_PORT: ${{ secrets.REDIS_PORT }}
  REDIS_PASS: ${{ secrets.REDIS_PASS }}
  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
  TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
  CF_APIKEY: ${{ secrets.CF_APIKEY }}
  CF_APIEMAIL: ${{ secrets.CF_APIEMAIL }}
  CF_ZONEID: ${{ secrets.CF_ZONEID }}
  CF_HOSTNAME: ${{ secrets.CF_HOSTNAME }}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Set up Masscan
      run: |
        sudo apt-get update
        sudo apt-get install -y masscan

    - name: Install dependencies
      run: |
        sudo pip install --upgrade --ignore-installed certifi urllib3
        sudo pip install -r requirements.txt
        sudo pip install redis

    - name: Run single-task-cfcdn-host
      env:
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
        REDIS_PASS: ${{ secrets.REDIS_PASS }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: |
        sudo chmod +x love-you
        sudo python3 cfcdn.py
