name: single-task-clean-check

on:
  push:
    branches:
      # - master
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]
  schedule:
    - cron: "0 1,12 * * *"  # Runs at 01:00 and 12:00 UTC

env:
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  REDIS_PORT: ${{ secrets.REDIS_PORT }}
  REDIS_PASS: ${{ secrets.REDIS_PASS }}
  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
  TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --ignore-installed certifi urllib3
          pip install -r requirements.txt
          pip install redis

      - name: Run single-task-clean-check
        run: |
          python3 checker.py

      - name: Check for changes
        id: git-status
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Push to origin master
        if: env.changed == 'true'
        run: |
          echo "Changes detected, pushing to repository..."
          git config --global user.name "fireinrain"
          git config --global user.email "lzyme.dev@gmail.com"
          git add asn/ README.md report.csv report.json
          git commit -m "$(date '+%Y-%m-%d')"
          git push origin master
